language: node_js
sudo: required
dist: trusty
node_js:
  - '10.9.0'
cache:
  yarn: true
  directories:
     - ./node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist/angular-zxcvbn-workspace
  on:
    branch: master
